/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { string } from '../schema';
import { BaseController } from './baseController';

export class AssetController extends BaseController {
  /**
   * Retrieve a binary file with the given assetId. The returned content type is always application/octet-
   * stream. If the service successfully retrieves the asset, HTTP 200 (OK) will be returned. If the
   * asset doesn’t exist, HTTP 404 (Not Found) will be returned. If you would like to see an error
   * message on the return, include application/json or application/xml in your desired format for the
   * Accept header.
   *
   * @param customerId
   * @param assetId
   * @return Response from the API call
   */
  async getAssetByCustomerID(
    customerId: string,
    assetId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      customerId: [customerId, string()],
      assetId: [assetId, string()],
    });
    req.appendTemplatePath`/aggregation/v1/customers/${mapped.customerId}/assets/${mapped.assetId}`;
    return req.call(requestOptions);
  }
}
