/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of AppPreRegMissingAppID
 */
interface AppPreRegMissingAppID {
  [key: string]: unknown;
}

export class AppPreRegMissingAppIDError extends ApiError<AppPreRegMissingAppID> {}
