/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of AppPreRegUsername
 */
interface AppPreRegUsername {
  [key: string]: unknown;
}

export class AppPreRegUsernameError extends ApiError<AppPreRegUsername> {}
