/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SetAppIDMapExists
 */
interface SetAppIDMapExists {
  [key: string]: unknown;
}

export class SetAppIDMapExistsError extends ApiError<SetAppIDMapExists> {}
