/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

/** The account owner information for the customer account */
export interface AccountOwnerV1 {
  /** The name of the account owner. In v1 this can be multiple account owners in one string. This is how the source data is returned from the institution. */
  ownerName: string;
  /** The address of the account owner */
  ownerAddress: string;
  [key: string]: unknown;
}

export const accountOwnerV1Schema: Schema<AccountOwnerV1> = expandoObject({
  ownerName: ['ownerName', string()],
  ownerAddress: ['ownerAddress', string()],
});
