/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, Schema, string } from '../schema';

export interface AppRegistrationResponse {
  /** An identifier to track the application registration request */
  preAppId: bigint;
  /** The status of the app registration request. When submitted starts as P for pending. */
  status: string;
  [key: string]: unknown;
}

export const appRegistrationResponseSchema: Schema<AppRegistrationResponse> = expandoObject(
  { preAppId: ['preAppId', bigint()], status: ['status', string()] }
);
