/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { AppStatusV1, appStatusV1Schema } from './appStatusV1';

/** The response for the Get App Registration Status endpoint which returns an array of App Status objects to be able to determine their registration status */
export interface AppStatusesV1 {
  /** List of App Status's */
  status: AppStatusV1[];
  [key: string]: unknown;
}

export const appStatusesV1Schema: Schema<AppStatusesV1> = expandoObject({
  status: ['status', array(lazy(() => appStatusV1Schema))],
});
