/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema } from '../schema';

export interface AssetSummaryForPrequalificationReports {
  /** Current balance of the account */
  currentBalance: number;
  /** The available balance for the account */
  availableBalance: number;
  /** Two month average daily balance of the account */
  twoMonthAverage: number;
  /** Six month average daily balance of the account */
  sixMonthAverage: number;
  /** Beginning balance of account per the time period in the report */
  beginningBalance: number;
  [key: string]: unknown;
}

export const assetSummaryForPrequalificationReportsSchema: Schema<AssetSummaryForPrequalificationReports> = expandoObject(
  {
    currentBalance: ['currentBalance', number()],
    availableBalance: ['availableBalance', number()],
    twoMonthAverage: ['twoMonthAverage', number()],
    sixMonthAverage: ['sixMonthAverage', number()],
    beginningBalance: ['beginningBalance', number()],
  }
);
