/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, optional, Schema } from '../schema';

export interface CadenceDetails {
  /** postedDate of the first deposit transaction */
  startDate?: bigint;
  /** postedDate of the final deposit transaction (omitted if status is active) */
  stopDate?: bigint;
  /** Number of days between the recurring deposits */
  days?: number;
  [key: string]: unknown;
}

export const cadenceDetailsSchema: Schema<CadenceDetails> = expandoObject({
  startDate: ['startDate', optional(bigint())],
  stopDate: ['stopDate', optional(bigint())],
  days: ['days', optional(number())],
});
