/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema } from '../schema';
import {
  CashFlowMonthlyCashFlowCreditSummaries,
  cashFlowMonthlyCashFlowCreditSummariesSchema,
} from './cashFlowMonthlyCashFlowCreditSummaries';

export interface CashFlowCashFlowCreditSummary {
  /** List of attributes for each month */
  monthlyCashFlowCreditSummaries: CashFlowMonthlyCashFlowCreditSummaries[];
  /** Sum of all credit transactions for each month for all accounts */
  twelveMonthCreditTotal: number;
  /** Sum of all monthly credit transactions without transfers for all accounts */
  twelveMonthCreditTotalLessTransfers: number;
  /** Six month sum of all credit transactions */
  sixMonthCreditTotal: number;
  /** Six month sum of all monthly credit transactions without transfers for all accounts */
  sixMonthCreditTotalLessTransfers: number;
  /** Two month sum of all credit transactions */
  twoMonthCreditTotal: number;
  /** Two month sum of all monthly credit transactions without transfers for all accounts */
  twoMonthCreditTotalLessTransfers: number;
  [key: string]: unknown;
}

export const cashFlowCashFlowCreditSummarySchema: Schema<CashFlowCashFlowCreditSummary> = expandoObject(
  {
    monthlyCashFlowCreditSummaries: [
      'monthlyCashFlowCreditSummaries',
      array(lazy(() => cashFlowMonthlyCashFlowCreditSummariesSchema)),
    ],
    twelveMonthCreditTotal: ['twelveMonthCreditTotal', number()],
    twelveMonthCreditTotalLessTransfers: [
      'twelveMonthCreditTotalLessTransfers',
      number(),
    ],
    sixMonthCreditTotal: ['sixMonthCreditTotal', number()],
    sixMonthCreditTotalLessTransfers: [
      'sixMonthCreditTotalLessTransfers',
      number(),
    ],
    twoMonthCreditTotal: ['twoMonthCreditTotal', number()],
    twoMonthCreditTotalLessTransfers: [
      'twoMonthCreditTotalLessTransfers',
      number(),
    ],
  }
);
