/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema, string } from '../schema';
import {
  CashFlowMonthlyCashFlowBalances,
  cashFlowMonthlyCashFlowBalancesSchema,
} from './cashFlowMonthlyCashFlowBalances';

export interface CashFlowCashflowBalance {
  /** List of attributes for each month */
  monthlyCashFlowBalances: CashFlowMonthlyCashFlowBalances[];
  /** Min daily balance across entire transaction history */
  minDailyBalance: number;
  /** Max Daily Balance across entire transaction history */
  maxDailyBalance: number;
  /** Average Daily Balance across twelve months for the account */
  twelveMonthAverageDailyBalance: number;
  /** Average Daily Balance across six months for the account */
  sixMonthAverageDailyBalance: number;
  /** Average Daily Balance across two months for the account */
  twoMonthAverageDailyBalance: number;
  /** Standard Deviation of Daily Balance across twelve months for the account */
  twelveMonthStandardDeviationOfDailyBalance: string;
  /** Standard Deviation of Daily Balance across six months for the account */
  sixMonthStandardDeviationOfDailyBalance: string;
  /** Standard Deviation of Daily Balance across two months for the account */
  twoMonthStandardDeviationOfDailyBalance: string;
  /** Number of Days Negative Balance over entire transaction history */
  numberDaysNegativeBalance: string;
  /** Number of Days positive balance over entire transaction history */
  numberOfDaysPositiveBalance: string;
  [key: string]: unknown;
}

export const cashFlowCashflowBalanceSchema: Schema<CashFlowCashflowBalance> = expandoObject(
  {
    monthlyCashFlowBalances: [
      'monthlyCashFlowBalances',
      array(lazy(() => cashFlowMonthlyCashFlowBalancesSchema)),
    ],
    minDailyBalance: ['minDailyBalance', number()],
    maxDailyBalance: ['maxDailyBalance', number()],
    twelveMonthAverageDailyBalance: [
      'twelveMonthAverageDailyBalance',
      number(),
    ],
    sixMonthAverageDailyBalance: ['sixMonthAverageDailyBalance', number()],
    twoMonthAverageDailyBalance: ['twoMonthAverageDailyBalance', number()],
    twelveMonthStandardDeviationOfDailyBalance: [
      'twelveMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    sixMonthStandardDeviationOfDailyBalance: [
      'sixMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    twoMonthStandardDeviationOfDailyBalance: [
      'twoMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    numberDaysNegativeBalance: ['numberDaysNegativeBalance', string()],
    numberOfDaysPositiveBalance: ['numberOfDaysPositiveBalance', string()],
  }
);
