/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema } from '../schema';

export interface CashFlowMonthlyCashFlowCharacteristicSummaries {
  /** One instance for each complete calendar month in the report */
  month: bigint;
  /** Total Credits - Total Debits by month across all accounts */
  totalCreditsLessTotalDebits: number;
  /** Total Credits - Total Debits by month (Without Transfers) across all accounts */
  totalCreditsLessTotalDebitsLessTransfers: number;
  /** Average transaction amount across all accounts */
  averageTransactionAmount: number;
  [key: string]: unknown;
}

export const cashFlowMonthlyCashFlowCharacteristicSummariesSchema: Schema<CashFlowMonthlyCashFlowCharacteristicSummaries> = expandoObject(
  {
    month: ['month', bigint()],
    totalCreditsLessTotalDebits: ['totalCreditsLessTotalDebits', number()],
    totalCreditsLessTotalDebitsLessTransfers: [
      'totalCreditsLessTotalDebitsLessTransfers',
      number(),
    ],
    averageTransactionAmount: ['averageTransactionAmount', number()],
  }
);
