/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema } from '../schema';
import {
  CashFlowMonthlycashflowDebits,
  cashFlowMonthlycashflowDebitsSchema,
} from './cashFlowMonthlycashflowDebits';

export interface CashFlowCashflowDebit {
  /** List of attributes for each month */
  monthlyCashFlowDebits: CashFlowMonthlycashflowDebits[];
  /** Sum of all monthly debit transactions for each month by account */
  twelveMonthDebitTotal: number;
  /** Sum of all monthly debit transactions without transfers for the account */
  twelveMonthDebitTotalLessTransfers: number;
  /** Six month sum of all debit transactions */
  sixMonthDebitTotal: number;
  /** Six month sum of all debit transactions without transfers for the account */
  sixMonthDebitTotalLessTransfers: number;
  /** Two month sum of all debit transactions */
  twoMonthDebitTotal: number;
  /** Two month sum of all debit transactions without transfers for the account */
  twoMonthDebitTotalLessTransfers: number;
  [key: string]: unknown;
}

export const cashFlowCashflowDebitSchema: Schema<CashFlowCashflowDebit> = expandoObject(
  {
    monthlyCashFlowDebits: [
      'monthlyCashFlowDebits',
      array(lazy(() => cashFlowMonthlycashflowDebitsSchema)),
    ],
    twelveMonthDebitTotal: ['twelveMonthDebitTotal', number()],
    twelveMonthDebitTotalLessTransfers: [
      'twelveMonthDebitTotalLessTransfers',
      number(),
    ],
    sixMonthDebitTotal: ['sixMonthDebitTotal', number()],
    sixMonthDebitTotalLessTransfers: [
      'sixMonthDebitTotalLessTransfers',
      number(),
    ],
    twoMonthDebitTotal: ['twoMonthDebitTotal', number()],
    twoMonthDebitTotalLessTransfers: [
      'twoMonthDebitTotalLessTransfers',
      number(),
    ],
  }
);
