/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema, string } from '../schema';
import {
  CashFlowMonthlyCashFlowBalanceSummaries,
  cashFlowMonthlyCashFlowBalanceSummariesSchema,
} from './cashFlowMonthlyCashFlowBalanceSummaries';

export interface CashFlowCashflowBalanceSummary {
  /** List of attributes for each month */
  monthlyCashFlowBalanceSummaries: CashFlowMonthlyCashFlowBalanceSummaries[];
  /** Min Daily Balance across entire transaction history  for all accounts */
  minDailyBalance: number;
  /** Max Daily Balance across entire transaction history for all accounts */
  maxDailyBalance: number;
  /** Average Daily Balance across twelve months for all accounts */
  twelveMonthAverageDailyBalance: number;
  /** Average Daily Balance across six months for all accounts */
  sixMonthAverageDailyBalance: number;
  /** Average Daily Balance across two months for all accounts */
  twoMonthAverageDailyBalance: number;
  /** Standard Deviation of Daily Balance across twelve months for all accounts */
  twelveMonthStandardDeviationOfDailyBalance: string;
  /** Standard Deviation of Daily Balance across six months for all accounts */
  sixMonthStandardDeviationOfDailyBalance: string;
  /** Standard Deviation of Daily Balance across two months for all accounts */
  twoMonthStandardDeviationOfDailyBalance: string;
  /** Number of Days Negative Balance over entire transaction history for all accounts */
  numberOfDaysNegativeBalance: string;
  /** Number of Days Positive Balance over entire transaction history for all accounts */
  numberOfDaysPositiveBalance: string;
  [key: string]: unknown;
}

export const cashFlowCashflowBalanceSummarySchema: Schema<CashFlowCashflowBalanceSummary> = expandoObject(
  {
    monthlyCashFlowBalanceSummaries: [
      'monthlyCashFlowBalanceSummaries',
      array(lazy(() => cashFlowMonthlyCashFlowBalanceSummariesSchema)),
    ],
    minDailyBalance: ['minDailyBalance', number()],
    maxDailyBalance: ['maxDailyBalance', number()],
    twelveMonthAverageDailyBalance: [
      'twelveMonthAverageDailyBalance',
      number(),
    ],
    sixMonthAverageDailyBalance: ['sixMonthAverageDailyBalance', number()],
    twoMonthAverageDailyBalance: ['twoMonthAverageDailyBalance', number()],
    twelveMonthStandardDeviationOfDailyBalance: [
      'twelveMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    sixMonthStandardDeviationOfDailyBalance: [
      'sixMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    twoMonthStandardDeviationOfDailyBalance: [
      'twoMonthStandardDeviationOfDailyBalance',
      string(),
    ],
    numberOfDaysNegativeBalance: ['numberOfDaysNegativeBalance', string()],
    numberOfDaysPositiveBalance: ['numberOfDaysPositiveBalance', string()],
  }
);
