/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  expandoObject,
  lazy,
  optional,
  Schema,
  string,
} from '../schema';
import { ChildInstitution, childInstitutionSchema } from './childInstitution';

export interface CertifiedInstitution {
  /** Institution's name */
  name: string;
  /** Institution's Id */
  id: bigint;
  /** Trans Agg Certification */
  transAgg: boolean;
  /** ACH Certification */
  ach: boolean;
  /** State Agg Certification */
  stateAgg: boolean;
  /** VOI Certification */
  voi: boolean;
  /** VOA Certification */
  voa: boolean;
  /** AHA Certification */
  aha: boolean;
  /** Account Balance Check (ABC) Certification */
  availBalance: boolean;
  /** Account Owner Certification */
  accountOwner: boolean;
  childInstitutions?: ChildInstitution[];
  [key: string]: unknown;
}

export const certifiedInstitutionSchema: Schema<CertifiedInstitution> = expandoObject(
  {
    name: ['name', string()],
    id: ['id', bigint()],
    transAgg: ['transAgg', boolean()],
    ach: ['ach', boolean()],
    stateAgg: ['stateAgg', boolean()],
    voi: ['voi', boolean()],
    voa: ['voa', boolean()],
    aha: ['aha', boolean()],
    availBalance: ['availBalance', boolean()],
    accountOwner: ['accountOwner', boolean()],
    childInstitutions: [
      'childInstitutions',
      optional(array(lazy(() => childInstitutionSchema))),
    ],
  }
);
