/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, string } from '../schema';

export interface ChildInstitution {
  /** The RSSD ID is a unique identifier assigned to financial institutions by the Federal Reserve. While the length of the RSSD ID varies by institution, it cannot exceed 10 numerical digits */
  rssd: number;
  /** The RSSD ID is a unique identifier assigned to financial institutions by the Federal Reserve. While the length of the RSSD ID varies by institution, it cannot exceed 10 numerical digits */
  parentRSSD: number;
  /** The name of the institution */
  name: string;
  /** Finicity’s institution ID */
  institutionId: number;
  [key: string]: unknown;
}

export const childInstitutionSchema: Schema<ChildInstitution> = expandoObject({
  rssd: ['rssd', number()],
  parentRSSD: ['parentRSSD', number()],
  name: ['name', string()],
  institutionId: ['institutionId', number()],
});
