/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, optional, Schema, string } from '../schema';

/** Customizable email details */
export interface ConnectEmailOptions {
  /** The email address you wish to receive the email */
  to: string;
  /** Phone number that will be listed for support in the email. This field is optional. This is also available in the Finicity Developer Portal. */
  supportPhone?: string;
  /** The “subject” line that will appear in user’s inboxes. Defaults to ‘Verify your Financial Information’ This field is optional. */
  subject?: string;
  /** The first name of the customer that will appear in the email This field is optional. */
  firstName?: string;
  /** The header color in the email. Defaults to dark blue This field is optional. This is also available in the Finicity Developer Portal. */
  brandColor?: string;
  /** A valid url that points to the logo you want to appear in the email. For optimal display, should have dimensions no greater than 110 pixels tall and 300 pixels wide This field is optional. This is also available in the Finicity Developer Portal. */
  brandLogo?: string;
  /** The name of your company that will appear in the email This field is optional. This is also available in the Finicity Developer Portal. */
  institutionName?: string;
  /** Address that will appear in the footer of the email This field is optional. This is also available in the Finicity Developer Portal. */
  institutionAddress?: string;
  /** Signature can be applied. In xml a separate line in signature is delineated by each tag. In json this is simply an array, e.g. “signature”: This field is optional. */
  signature?: string[];
  [key: string]: unknown;
}

export const connectEmailOptionsSchema: Schema<ConnectEmailOptions> = expandoObject(
  {
    to: ['to', string()],
    supportPhone: ['supportPhone', optional(string())],
    subject: ['subject', optional(string())],
    firstName: ['firstName', optional(string())],
    brandColor: ['brandColor', optional(string())],
    brandLogo: ['brandLogo', optional(string())],
    institutionName: ['institutionName', optional(string())],
    institutionAddress: ['institutionAddress', optional(string())],
    signature: ['signature', optional(array(string()))],
  }
);
