/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface ConsumerAttributesDataDateRange {
  /** The `From` date of the date range for the report. */
  from: string;
  /** The `To` date of the date range for the report. */
  to: string;
  [key: string]: unknown;
}

export const consumerAttributesDataDateRangeSchema: Schema<ConsumerAttributesDataDateRange> = expandoObject(
  { from: ['From', string()], to: ['To', string()] }
);
