/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, unknown } from '../schema';

export interface ConsumerAttributesAssetsAccount {
  /** Account closing balance by month. */
  monthlyClosingBalance?: unknown;
  /** Account minimum balance by month. */
  monthlyMinimumBalance?: unknown;
  /** Account maximum balance by month. */
  monthlyMaximumBalance?: unknown;
  /** Account maximum balance by month. */
  monthlyAverageBalance?: unknown;
  /** Standard deviation of balance by account. */
  monthlyStandardDeviationOfBalance?: unknown;
  /** Number of days in a month with a positive account balance. */
  monthlyDaysWithPositiveBalance?: unknown;
  /** Number of days in a month with a negative account balance. */
  monthlyDaysWithNegativeBalance?: unknown;
  /** Two month average balance by account. */
  monthlyTwoMonthAverageBalance?: unknown;
  /** Six month average balance by account. */
  monthlySixMonthAverageBalance?: unknown;
  /** Twelve month average balance by account. */
  twelveMonthAverageBalance?: unknown;
  /** Standard deviation of account balance across two months. */
  twoMonthStandardDeviationOfBalance?: unknown;
  /** Standard deviation of account balance across six months. */
  sixMonthStandardDeviationOfBalance?: unknown;
  /** Standard deviation of account balance across twelve months. */
  twelveMonthStandardDeviationOfBalance?: unknown;
  [key: string]: unknown;
}

export const consumerAttributesAssetsAccountSchema: Schema<ConsumerAttributesAssetsAccount> = expandoObject(
  {
    monthlyClosingBalance: ['monthlyClosingBalance', unknown()],
    monthlyMinimumBalance: ['monthlyMinimumBalance', unknown()],
    monthlyMaximumBalance: ['monthlyMaximumBalance', unknown()],
    monthlyAverageBalance: ['monthlyAverageBalance', unknown()],
    monthlyStandardDeviationOfBalance: [
      'monthlyStandardDeviationOfBalance',
      unknown(),
    ],
    monthlyDaysWithPositiveBalance: [
      'monthlyDaysWithPositiveBalance',
      unknown(),
    ],
    monthlyDaysWithNegativeBalance: [
      'monthlyDaysWithNegativeBalance',
      unknown(),
    ],
    monthlyTwoMonthAverageBalance: ['monthlyTwoMonthAverageBalance', unknown()],
    monthlySixMonthAverageBalance: ['monthlySixMonthAverageBalance', unknown()],
    twelveMonthAverageBalance: ['twelveMonthAverageBalance', unknown()],
    twoMonthStandardDeviationOfBalance: [
      'twoMonthStandardDeviationOfBalance',
      unknown(),
    ],
    sixMonthStandardDeviationOfBalance: [
      'sixMonthStandardDeviationOfBalance',
      unknown(),
    ],
    twelveMonthStandardDeviationOfBalance: [
      'twelveMonthStandardDeviationOfBalance',
      unknown(),
    ],
  }
);
