/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema } from '../schema';
import { MonthlyNetAmount, monthlyNetAmountSchema } from './monthlyNetAmount';

export interface ConsumerAttributesDataNetAmount {
  /** Monthly customer net amount (income less expenses). */
  monthlyNetAmount: MonthlyNetAmount;
  [key: string]: unknown;
}

export const consumerAttributesDataNetAmountSchema: Schema<ConsumerAttributesDataNetAmount> = expandoObject(
  { monthlyNetAmount: ['monthlyNetAmount', lazy(() => monthlyNetAmountSchema)] }
);
