/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  expandoObject,
  number,
  optional,
  Schema,
  string,
} from '../schema';

/** Create a text transaction for TxPush testing */
export interface CreateTxpushTestTransactionRequest {
  /** The amount of the transaction */
  amount: number;
  /** The description of the transaction */
  description: string;
  /** active or pending (optional) */
  status?: string;
  /** An optional timestamp for the transaction’s posted date value for this transaction (see Handling Dates and Times). Timestamp must be no more than 6 months from the current date. */
  postedDate: bigint;
  /** An optional timestamp for the transaction’s posted date value for this transaction (see Handling Dates and Times) */
  transactionDate: bigint;
  [key: string]: unknown;
}

export const createTxpushTestTransactionRequestSchema: Schema<CreateTxpushTestTransactionRequest> = expandoObject(
  {
    amount: ['amount', number()],
    description: ['description', string()],
    status: ['status', optional(string())],
    postedDate: ['postedDate', bigint()],
    transactionDate: ['transactionDate', bigint()],
  }
);
