/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, Schema } from '../schema';

/** Response for TxPush test transaction */
export interface CreateTxpushTestTransactionResponse {
  /** The ID of the new transaction record */
  id: bigint;
  /** A timestamp of when the transaction was added (see Handling Dates and Times) */
  createdDate: bigint;
  [key: string]: unknown;
}

export const createTxpushTestTransactionResponseSchema: Schema<CreateTxpushTestTransactionResponse> = expandoObject(
  { id: ['id', bigint()], createdDate: ['createdDate', bigint()] }
);
