/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CustomerTypeEnum
 */
export enum CustomerTypeEnum {
  Active = 'active',
  Testing = 'testing',
}

/**
 * Schema for CustomerTypeEnum
 */
export const customerTypeEnumSchema: Schema<CustomerTypeEnum> = stringEnum(CustomerTypeEnum);
