/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, expandoObject, lazy, Schema, string } from '../schema';
import {
  PayrollDeductionsRecord,
  payrollDeductionsRecordSchema,
} from './payrollDeductionsRecord';
import {
  PayrollDirectDepositRecord,
  payrollDirectDepositRecordSchema,
} from './payrollDirectDepositRecord';
import {
  PayrollEarningsRecord,
  payrollEarningsRecordSchema,
} from './payrollEarningsRecord';
import {
  PayrollMainPaystatementFields,
  payrollMainPaystatementFieldsSchema,
} from './payrollMainPaystatementFields';

export interface DirectPayStatementFields {
  /** An id for the income and employment details from a pay period. */
  payrollPayHistoryId: string;
  /** The payment history from the last pay period of the year. If there are 3 years of pay history, then the value is true for 3 payment histories. */
  lastPayPeriodIndicator: boolean;
  mainPayStatementFields: PayrollMainPaystatementFields;
  earnings: PayrollEarningsRecord[];
  deductions: PayrollDeductionsRecord[];
  directDeposits: PayrollDirectDepositRecord[];
  [key: string]: unknown;
}

export const directPayStatementFieldsSchema: Schema<DirectPayStatementFields> = expandoObject(
  {
    payrollPayHistoryId: ['payrollPayHistoryId', string()],
    lastPayPeriodIndicator: ['lastPayPeriodIndicator', boolean()],
    mainPayStatementFields: [
      'mainPayStatementFields',
      lazy(() => payrollMainPaystatementFieldsSchema),
    ],
    earnings: ['earnings', array(lazy(() => payrollEarningsRecordSchema))],
    deductions: [
      'deductions',
      array(lazy(() => payrollDeductionsRecordSchema)),
    ],
    directDeposits: [
      'directDeposits',
      array(lazy(() => payrollDirectDepositRecordSchema)),
    ],
  }
);
