/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

export interface DirectDeposit {
  /** The amount of the deposit. */
  amountCurrent?: number;
  /** The last four numbers of the account the deposit went into. */
  accountLastFour?: string;
  [key: string]: unknown;
}

export const directDepositSchema: Schema<DirectDeposit> = expandoObject({
  amountCurrent: ['amountCurrent', optional(number())],
  accountLastFour: ['accountLastFour', optional(string())],
});
