/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Employee {
  /** The name of the employee */
  name?: string;
  [key: string]: unknown;
}

export const employeeSchema: Schema<Employee> = expandoObject({
  name: ['name', optional(string())],
});
