/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema, string } from '../schema';
import {
  ConnectEmailOptions,
  connectEmailOptionsSchema,
} from './connectEmailOptions';

/** Response from create url call */
export interface GenerateConnectEmailResponse {
  /** The generated Connect URL */
  link: string;
  emailConfig: ConnectEmailOptions;
  [key: string]: unknown;
}

export const generateConnectEmailResponseSchema: Schema<GenerateConnectEmailResponse> = expandoObject(
  {
    link: ['link', string()],
    emailConfig: ['emailConfig', lazy(() => connectEmailOptionsSchema)],
  }
);
