/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, lazy, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';
import {
  VOIEWithStatementConstraints,
  vOIEWithStatementConstraintsSchema,
} from './vOIEWithStatementConstraints';

export interface GenerateVOIEPaystubReportResponse {
  /** Finicity's report ID */
  id: string;
  /** Finicity’s portfolio ID associated with the consumer on the report. */
  portfolioId: string;
  /** Customer type */
  customerType: string;
  /** Finicity ID for the customer */
  customerId: bigint;
  /** Unique requestId for this specific call request */
  requestId: string;
  /** Name of Finicity partner requesting the report */
  requesterName: string;
  /** The date the report was generated */
  createdDate: bigint;
  /** Title of the report */
  title: string;
  /** Finicity report consumer ID (max length 32 characters) */
  consumerId: string;
  /** Last 4 digits of the report consumer’s Social Security number */
  consumerSsn: string;
  constraints: VOIEWithStatementConstraints;
  /** Report type */
  type: TypeEnum;
  /** inProgress, success, or failure */
  status: string;
  [key: string]: unknown;
}

export const generateVOIEPaystubReportResponseSchema: Schema<GenerateVOIEPaystubReportResponse> = expandoObject(
  {
    id: ['id', string()],
    portfolioId: ['portfolioId', string()],
    customerType: ['customerType', string()],
    customerId: ['customerId', bigint()],
    requestId: ['requestId', string()],
    requesterName: ['requesterName', string()],
    createdDate: ['createdDate', bigint()],
    title: ['title', string()],
    consumerId: ['consumerId', string()],
    consumerSsn: ['consumerSsn', string()],
    constraints: [
      'constraints',
      lazy(() => vOIEWithStatementConstraintsSchema),
    ],
    type: ['type', typeEnumSchema],
    status: ['status', string()],
  }
);
