/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, Schema, string, unknown } from '../schema';

export interface GenerateConnectEmailResponseMultiBorrowers {
  /** The URL generated to send a Connect email */
  links: string[];
  /** The configuration used to generate the Connect email. */
  emailConfig?: unknown;
  [key: string]: unknown;
}

export const generateConnectEmailResponseMultiBorrowersSchema: Schema<GenerateConnectEmailResponseMultiBorrowers> = expandoObject(
  { links: ['links', array(string())], emailConfig: ['emailConfig', unknown()] }
);
