/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface GenerateConsumerAttributesReponse {
  /** An analytic ID generated for the requested report. */
  analyticId: string;
  /** The date and time (Epoch) that the data analytics report generated. */
  createdDate: string;
  [key: string]: unknown;
}

export const generateConsumerAttributesReponseSchema: Schema<GenerateConsumerAttributesReponse> = expandoObject(
  {
    analyticId: ['analytic_id', string()],
    createdDate: ['created_date', string()],
  }
);
