/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, expandoObject, lazy, number, Schema } from '../schema';
import { Customer, customerSchema } from './customer';

/** Response For Get Customers Endpoint */
export interface GetCustomersResponse {
  /** Total number of records matching search criteria */
  found: number;
  /** Number of records in this response */
  displaying: number;
  /** true if this response does not contain the last record in the result set */
  moreAvailable: boolean;
  /** List of customer records */
  customers: Customer[];
  [key: string]: unknown;
}

export const getCustomersResponseSchema: Schema<GetCustomersResponse> = expandoObject(
  {
    found: ['found', number()],
    displaying: ['displaying', number()],
    moreAvailable: ['moreAvailable', boolean()],
    customers: ['customers', array(lazy(() => customerSchema))],
  }
);
