/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema } from '../schema';

export interface InterviewAccounts {
  /** The accountId of the selected account during the Account Interview process. */
  id: bigint;
  /** The customer entered value of the amount deposited into the account during the Account Interview process. This is an optional field. */
  amount: number;
  [key: string]: unknown;
}

export const interviewAccountsSchema: Schema<InterviewAccounts> = expandoObject(
  { id: ['id', bigint()], amount: ['amount', number()] }
);
