/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, Schema, unknown } from '../schema';

export interface ListConsumerAttributesResponse {
  /** A list of all analytic IDs generated for a customer, The date and time (Epoch) that the data analytics report generated.and used to Get the Consumer Attributes report. */
  analyticIds: unknown[];
  [key: string]: unknown;
}

export const listConsumerAttributesResponseSchema: Schema<ListConsumerAttributesResponse> = expandoObject(
  { analyticIds: ['analytic_ids', array(unknown())] }
);
