/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  expandoObject,
  lazy,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import {
  LoanPaymentDetailsGroupDetail,
  loanPaymentDetailsGroupDetailSchema,
} from './loanPaymentDetailsGroupDetail';
import {
  LoanPaymentDetailsLoanDetail,
  loanPaymentDetailsLoanDetailSchema,
} from './loanPaymentDetailsLoanDetail';

export interface LoanPaymentDetailsAccountDetail {
  /** Finicity's ID of the Student Loan Account */
  accountId: string;
  /** Institution's ID of the Student Loan Account */
  accountNumber: string;
  /** The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number. */
  accountPaymentNumber: string;
  /** The payment address to which send manual payments should be sent */
  accountPaymentAddress: string;
  /** The payoff amount for the account */
  accountFuturePayoffAmount?: number;
  /** The date to which the `Future Payoff Amount` applies */
  accountFuturePayoffDate?: string;
  groupDetail?: LoanPaymentDetailsGroupDetail[];
  loanDetail?: LoanPaymentDetailsLoanDetail[];
  [key: string]: unknown;
}

export const loanPaymentDetailsAccountDetailSchema: Schema<LoanPaymentDetailsAccountDetail> = expandoObject(
  {
    accountId: ['accountId', string()],
    accountNumber: ['accountNumber', string()],
    accountPaymentNumber: ['accountPaymentNumber', string()],
    accountPaymentAddress: ['accountPaymentAddress', string()],
    accountFuturePayoffAmount: [
      'accountFuturePayoffAmount',
      optional(number()),
    ],
    accountFuturePayoffDate: ['accountFuturePayoffDate', optional(string())],
    groupDetail: [
      'groupDetail',
      optional(array(lazy(() => loanPaymentDetailsGroupDetailSchema))),
    ],
    loanDetail: [
      'loanDetail',
      optional(array(lazy(() => loanPaymentDetailsLoanDetailSchema))),
    ],
  }
);
