/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface ModifyPartnerCredentials {
  /** Partner ID from Developer Portal */
  partnerId: string;
  /** Partner Secret from Developer Portal */
  partnerSecret: string;
  /** The Value For The New Partner Secret To Be Change To */
  newPartnerSecret: string;
  [key: string]: unknown;
}

export const modifyPartnerCredentialsSchema: Schema<ModifyPartnerCredentials> = expandoObject(
  {
    partnerId: ['partnerId', string()],
    partnerSecret: ['partnerSecret', string()],
    newPartnerSecret: ['newPartnerSecret', string()],
  }
);
