/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, unknown } from '../schema';

export interface MonthlyNetAmount {
  netAmount?: unknown;
  [key: string]: unknown;
}

export const monthlyNetAmountSchema: Schema<MonthlyNetAmount> = expandoObject({
  netAmount: ['NetAmount', unknown()],
});
