/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema } from '../schema';

export interface NetMonthly {
  /** Timestamp for the first day of this month */
  month: bigint;
  /** Total income during the given month, across all income streams */
  net: number;
  [key: string]: unknown;
}

export const netMonthlySchema: Schema<NetMonthly> = expandoObject({
  month: ['month', bigint()],
  net: ['net', number()],
});
