/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema } from '../schema';

export interface PayrollMonthlyIncomeRecord {
  /** The estimated monthly base pay amount for the employment record, as calculated by Finicity. */
  estimatedMonthlyBasePay?: number;
  /** The estimated monthly overtime pay amount for the employment record, as calculated by Finicity. */
  estimatedMonthlyOvertimePay?: number;
  /** The estimated monthly bonus pay amount for the employment record, as calculated by Finicity. */
  estimatedMonthlyBonusPay?: number;
  /** The estimated monthly other pay amount for the employment record, as calculated by Finicity. */
  estimatedMonthlyOtherPay?: number;
  [key: string]: unknown;
}

export const payrollMonthlyIncomeRecordSchema: Schema<PayrollMonthlyIncomeRecord> = expandoObject(
  {
    estimatedMonthlyBasePay: ['estimatedMonthlyBasePay', optional(number())],
    estimatedMonthlyOvertimePay: [
      'estimatedMonthlyOvertimePay',
      optional(number()),
    ],
    estimatedMonthlyBonusPay: ['estimatedMonthlyBonusPay', optional(number())],
    estimatedMonthlyOtherPay: ['estimatedMonthlyOtherPay', optional(number())],
  }
);
