/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

export interface PayrollDirectDepositRecord {
  /** Bank account type: <br> * `Checking` <br> * `Savings` <br> * `Loan`:  Loan account employee chooses to direct a portion of their net pay to help pay off a loan */
  accountTypeCode?: string;
  /** Direct deposit amount */
  amount?: number;
  /** Last four digits of the deposit account number */
  accountLastFour?: string;
  /** Routing number for the deposit account */
  routingNumber?: string;
  [key: string]: unknown;
}

export const payrollDirectDepositRecordSchema: Schema<PayrollDirectDepositRecord> = expandoObject(
  {
    accountTypeCode: ['accountTypeCode', optional(string())],
    amount: ['amount', optional(number())],
    accountLastFour: ['accountLastFour', optional(string())],
    routingNumber: ['routingNumber', optional(string())],
  }
);
