/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, lazy, Schema, string } from '../schema';
import {
  PayrollEmployeeRecord,
  payrollEmployeeRecordSchema,
} from './payrollEmployeeRecord';
import {
  PayrollEmploymentRecord,
  payrollEmploymentRecordSchema,
} from './payrollEmploymentRecord';
import {
  PayrollIncomeRecord,
  payrollIncomeRecordSchema,
} from './payrollIncomeRecord';

export interface PayrollEmploymentHistory {
  /** The last time the payroll data was updated in the payroll provider's system */
  asOfDate: bigint;
  /** Name of the employer as stated by the employer in the payroll system. */
  employerName: string;
  /** The name of the payroll source where the data was retrieved. */
  payrollSource: string;
  employee: PayrollEmployeeRecord;
  employment: PayrollEmploymentRecord;
  income: PayrollIncomeRecord;
  [key: string]: unknown;
}

export const payrollEmploymentHistorySchema: Schema<PayrollEmploymentHistory> = expandoObject(
  {
    asOfDate: ['asOfDate', bigint()],
    employerName: ['employerName', string()],
    payrollSource: ['payrollSource', string()],
    employee: ['employee', lazy(() => payrollEmployeeRecordSchema)],
    employment: ['employment', lazy(() => payrollEmploymentRecordSchema)],
    income: ['income', lazy(() => payrollIncomeRecordSchema)],
  }
);
