/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, Schema, string } from '../schema';

export interface PayrollReportData {
  /** An id to identify the data retrieved from the payroll providers for the report. */
  payrollDataRetrievalId: string;
  /** An array of employer names that the consumer submitted after completing the Connect application. */
  employerNames: string[];
  /** The `reportId` of the original VOIE Payroll report. */
  reportId: string;
  [key: string]: unknown;
}

export const payrollReportDataSchema: Schema<PayrollReportData> = expandoObject(
  {
    payrollDataRetrievalId: ['payrollDataRetrievalId', string()],
    employerNames: ['employerNames', array(string())],
    reportId: ['reportId', string()],
  }
);
