/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface PayrollEmployeeAddress {
  /** Employee address as stated by the employer in the payroll system */
  address1?: string;
  /** Employee city as stated by the employer in the payroll system */
  city?: string;
  /** Employee state as stated by the employer in the payroll system */
  state?: string;
  /** Employee zip code as stated by the employer in the payroll system */
  zip?: string;
  [key: string]: unknown;
}

export const payrollEmployeeAddressSchema: Schema<PayrollEmployeeAddress> = expandoObject(
  {
    address1: ['address1', optional(string())],
    city: ['city', optional(string())],
    state: ['state', optional(string())],
    zip: ['zip', optional(string())],
  }
);
