/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  expandoObject,
  lazy,
  optional,
  Schema,
} from '../schema';
import { PayrollData, payrollDataSchema } from './payrollData';
import {
  ReportCustomField,
  reportCustomFieldSchema,
} from './reportCustomField';

export interface PayrollReportConstraints {
  payrollData: PayrollData;
  /** Designate up to 5 custom fields that you would like associated with the report upon generation by providing a label for the field and a value for the field. Set the shown variable to true if you want the custom field to display in the PDF reports. Set the shown variable to false to limit seeing the variable to JSON, XML report but not in the PDF report. All custom fields will display in the Reseller Billing endpoint.  This is optional. */
  reportCustomFields?: ReportCustomField[];
  /** Limits the pay statement history in the VOIE – Paryroll report by entering a pay statement history start date. <br> <br> Pay statements are included if the `payDate` of the statement is equal to or greater than the start date. */
  payStatementsFromDate?: bigint;
  [key: string]: unknown;
}

export const payrollReportConstraintsSchema: Schema<PayrollReportConstraints> = expandoObject(
  {
    payrollData: ['payrollData', lazy(() => payrollDataSchema)],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
    payStatementsFromDate: ['payStatementsFromDate', optional(bigint())],
  }
);
