/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  expandoObject,
  lazy,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PayrollEmployerAddress,
  payrollEmployerAddressSchema,
} from './payrollEmployerAddress';

export interface PayrollEmploymentRecord {
  /** Name of the employer as stated by the employer in the payroll system. */
  employerName: string;
  /** Employer identification number (EIN) */
  legalEntityId?: string;
  /** The original hired date of an employee at the company. */
  originalHireDate?: bigint;
  /** If an employee leaves the company and returns later, then the employer states the latest hire date at the company. */
  latestHireDate?: bigint;
  /** The most recent pay date from an employer. */
  latestPayDate: bigint;
  /** The number of days since an employee was last paid. */
  daysSinceLastPay: number;
  /** The number of pay cadences an employee has not been paid; determined by the pay frequency. */
  numberPayCadenceWithoutPay: number;
  /** The date an employee ended their employment at the company. */
  employmentEndDate?: bigint;
  /** The length of time an employee has been employed with that employer in ISO 8601 format (eg P1Y6M0D) */
  employmentDuration?: string;
  /** Array of addresses */
  employerAddress?: PayrollEmployerAddress[];
  /** Status codes: `A` - Active, `NLE` - No Longer Employed, `L` - Leave */
  employmentStatusCode: string;
  /** Status name: `Active`, `No Longer Employed`, or `Leave` */
  employmentStatusName: string;
  /** The abbreviate code for the employment level names (workLevelName) that we receive from the employer. */
  workLevelCode?: string;
  /** The employment level name is whatever we receive from the employer, such as full time, part time, temp, contractor, and more. */
  workLevelName?: string;
  /** The categorized work level status. Enumerations are: <br> * `Temporary` <br> * `Seasonal` <br> * `Retired` <br> * `Student` <br> * `Full Time` <br> * `Part Time` <br> * `Unspecified` <br> This is a new field, currently enabled only for testing reports. It will be added for all reports in August 2021. */
  workLevelStatus: string;
  /** Employee job title */
  positionTitle?: string;
  /** The length of time an employee has been employed at their current or latest position for this employment in ISO 8601 format (eg P1Y6M0D) */
  positionDuration?: string;
  [key: string]: unknown;
}

export const payrollEmploymentRecordSchema: Schema<PayrollEmploymentRecord> = expandoObject(
  {
    employerName: ['employerName', string()],
    legalEntityId: ['legalEntityId', optional(string())],
    originalHireDate: ['originalHireDate', optional(bigint())],
    latestHireDate: ['latestHireDate', optional(bigint())],
    latestPayDate: ['latestPayDate', bigint()],
    daysSinceLastPay: ['daysSinceLastPay', number()],
    numberPayCadenceWithoutPay: ['numberPayCadenceWithoutPay', number()],
    employmentEndDate: ['employmentEndDate', optional(bigint())],
    employmentDuration: ['employmentDuration', optional(string())],
    employerAddress: [
      'employerAddress',
      optional(array(lazy(() => payrollEmployerAddressSchema))),
    ],
    employmentStatusCode: ['employmentStatusCode', string()],
    employmentStatusName: ['employmentStatusName', string()],
    workLevelCode: ['workLevelCode', optional(string())],
    workLevelName: ['workLevelName', optional(string())],
    workLevelStatus: ['workLevelStatus', string()],
    positionTitle: ['positionTitle', optional(string())],
    positionDuration: ['positionDuration', optional(string())],
  }
);
