/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema } from '../schema';

export interface PaystubMonthlyIncomeRecord {
  /** The estimated monthly base pay amount for the employment from the paystub, calculated by Finicity. */
  estimatedMonthlyBasePay?: number;
  /** The estimated monthly overtime pay amount for the employment from the paystub, calculated by Finicity. */
  estimatedMonthlyOvertimePay?: number;
  /** The estimated monthly bonus pay amount for the employment from the paystub, calculated by Finicity. */
  estimatedMonthlyBonusPay?: number;
  /** The estimated commission bonus pay amount for the employment from the paystub, calculated by Finicity. */
  estimatedMonthlyCommissionPay?: number;
  [key: string]: unknown;
}

export const paystubMonthlyIncomeRecordSchema: Schema<PaystubMonthlyIncomeRecord> = expandoObject(
  {
    estimatedMonthlyBasePay: ['estimatedMonthlyBasePay', optional(number())],
    estimatedMonthlyOvertimePay: [
      'estimatedMonthlyOvertimePay',
      optional(number()),
    ],
    estimatedMonthlyBonusPay: ['estimatedMonthlyBonusPay', optional(number())],
    estimatedMonthlyCommissionPay: [
      'estimatedMonthlyCommissionPay',
      optional(number()),
    ],
  }
);
