/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayStatEarningsCategorizationTypeEnum
 */
export enum PayStatEarningsCategorizationTypeEnum {
  Bereavement = 'bereavement',
  Bonus = 'bonus',
  Commission = 'commission',
  Holiday = 'holiday',
  JuryDuty = 'jury duty',
  Overtime = 'overtime',
  Pension = 'pension',
  Pto = 'pto',
  Regular = 'regular',
  Sick = 'sick',
  Tips = 'tips',
  Unknown = 'unknown',
  Vacation = 'vacation',
  Reimbursement = 'reimbursement',
  Stock = 'stock',
  Benefit = 'benefit',
}

/**
 * Schema for PayStatEarningsCategorizationTypeEnum
 */
export const payStatEarningsCategorizationTypeEnumSchema: Schema<PayStatEarningsCategorizationTypeEnum> = stringEnum(PayStatEarningsCategorizationTypeEnum);
