/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  expandoObject,
  lazy,
  optional,
  Schema,
  string,
} from '../schema';
import { ErrorMessage, errorMessageSchema } from './errorMessage';
import {
  PayrollReportRefreshResponseConstraints,
  payrollReportRefreshResponseConstraintsSchema,
} from './payrollReportRefreshResponseConstraints';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface RefreshVOIEPayrollReportResponse {
  /** Finicity's report ID */
  id: string;
  /** Finicity ID for the customer */
  customerId: bigint;
  /** Finicity report consumer ID (max length 32 characters) */
  consumerId: string;
  /** Last 4 digits of the report consumer’s Social Security number */
  consumerSsn: string;
  /** Name of Finicity partner requesting the report */
  requesterName: string;
  /** Unique requestId for this specific call request */
  requestId: string;
  /** Report type */
  type: TypeEnum;
  /** inProgress, success, or failure */
  status: string;
  errors?: ErrorMessage[];
  /** The date the report was generated */
  createdDate: bigint;
  constraints: PayrollReportRefreshResponseConstraints;
  /** Customer type */
  customerType: string;
  /** Title of the report */
  title: string;
  /** Finicity’s portfolio ID associated with the consumer on the report. */
  portfolioId: string;
  [key: string]: unknown;
}

export const refreshVOIEPayrollReportResponseSchema: Schema<RefreshVOIEPayrollReportResponse> = expandoObject(
  {
    id: ['id', string()],
    customerId: ['customerId', bigint()],
    consumerId: ['consumerId', string()],
    consumerSsn: ['consumerSsn', string()],
    requesterName: ['requesterName', string()],
    requestId: ['requestId', string()],
    type: ['type', typeEnumSchema],
    status: ['status', string()],
    errors: ['errors', optional(array(lazy(() => errorMessageSchema)))],
    createdDate: ['createdDate', bigint()],
    constraints: [
      'constraints',
      lazy(() => payrollReportRefreshResponseConstraintsSchema),
    ],
    customerType: ['customerType', string()],
    title: ['title', string()],
    portfolioId: ['portfolioId', string()],
  }
);
