/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, expandoObject, Schema, string } from '../schema';

export interface ReportCustomFields {
  /** The label for the custom field */
  label: string;
  /** The value of the custom field */
  value: string;
  /** Indicates whether the field should be shown in the consumer version of the report */
  shown: boolean;
  [key: string]: unknown;
}

export const reportCustomFieldsSchema: Schema<ReportCustomFields> = expandoObject(
  {
    label: ['label', string()],
    value: ['value', string()],
    shown: ['shown', boolean()],
  }
);
