/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema } from '../schema';

/** Report Income Estimate */
export interface ReportIncomeEstimate {
  netAnnual: number;
  projectedNetAnnual: number;
  estimatedGrossAnnual: number;
  projectedGrossAnnual: number;
  [key: string]: unknown;
}

export const reportIncomeEstimateSchema: Schema<ReportIncomeEstimate> = expandoObject(
  {
    netAnnual: ['netAnnual', number()],
    projectedNetAnnual: ['projectedNetAnnual', number()],
    estimatedGrossAnnual: ['estimatedGrossAnnual', number()],
    projectedGrossAnnual: ['projectedGrossAnnual', number()],
  }
);
