/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, expandoObject, Schema, string } from '../schema';

export interface ReportCustomField1 {
  label: string;
  value: string;
  shown: boolean;
  [key: string]: unknown;
}

export const reportCustomField1Schema: Schema<ReportCustomField1> = expandoObject(
  {
    label: ['label', string()],
    value: ['value', string()],
    shown: ['shown', boolean()],
  }
);
