/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  expandoObject,
  lazy,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ReportCustomField,
  reportCustomFieldSchema,
} from './reportCustomField';

export interface ReportConstraints {
  /** Specific accountIds to be included in the new report. */
  accountIds?: string[];
  /** The fromDate parameter is an Epoch Timestamp (in seconds), such as “1494449017”.  Without this parameter, the report defaults to 6 months if available. Example: ?fromDate={fromDate} If included, the epoch timestamp should be 10 digits long and be within two years of the present day. Extending the epoch timestamp beyond 10 digits will default back to six months of data.  This query is optional */
  fromDate?: bigint;
  /** Designate up to 5 custom fields that you would like associated with the report upon generation by providing a label for the field and a value for the field. Set the shown variable to true if you want the custom field to display in the PDF reports. Set the shown variable to false to limit seeing the variable to JSON, XML report but not in the PDF report. All custom fields will display in the Reseller Billing endpoint.  This is optional. */
  reportCustomFields?: ReportCustomField[];
  /** Include the non-sufficient funds (NSF) summary JSON and the NSF summary PDF section in the report. <br> <br>  **Data included**: <br> <br>  * Account  <br> <br>  * Total number of NSF funds  <br> <br>  * Days since the most recent NFS funds fee */
  showNsf?: boolean;
  [key: string]: unknown;
}

export const reportConstraintsSchema: Schema<ReportConstraints> = expandoObject(
  {
    accountIds: ['accountIds', optional(array(string()))],
    fromDate: ['fromDate', optional(bigint())],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
    showNsf: ['showNsf', optional(boolean())],
  }
);
