/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, optional, Schema } from '../schema';

export interface StatementReportData {
  /** Specify the account to retrieve the statement for and display in the report. */
  accountId: bigint;
  /** Index of statement to retrieve (default is 1, maximum is 6) */
  index?: bigint;
  [key: string]: unknown;
}

export const statementReportDataSchema: Schema<StatementReportData> = expandoObject(
  { accountId: ['accountId', bigint()], index: ['index', optional(bigint())] }
);
