/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface StorePayStatementResponse {
  /** The asset ID of the stored pay statement */
  assetId: string;
  [key: string]: unknown;
}

export const storePayStatementResponseSchema: Schema<StorePayStatementResponse> = expandoObject(
  { assetId: ['assetId', string()] }
);
