/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface StorePayStatementRequest {
  /** The label to be associated with the pay statement: <br> * `lastPayPeriod` This label will allow the paystub to go through data extraction. This is the default label that should be used for our VOIE - Paystub products. <br> * `lastPayPeriodMinusOne` The second most recent pay statement. <br> * `lastPayPeriodMinusTwo` The third most recent pay statement. <br> * `previousYearLastPayPeriod`  Last pay statement of the previous calendar year. <br> * `previousYear2LastPayPeriod`  Last pay statement of the calendar year 2 years prior. <br> * `earliestPayPeriod`  The earliest pay statement. */
  label: string;
  /** The base 64 encoded value for the pay statement. Finicity supported file types are .pdf, .jpg, or .png. */
  statement: string;
  [key: string]: unknown;
}

export const storePayStatementRequestSchema: Schema<StorePayStatementRequest> = expandoObject(
  { label: ['label', string()], statement: ['statement', string()] }
);
