/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  expandoObject,
  lazy,
  number,
  Schema,
  string,
} from '../schema';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum';
import {
  TransactionsReportTransaction,
  transactionsReportTransactionSchema,
} from './transactionsReportTransaction';

/** The fields used for the Transaction History Report (CRA products). */
export interface TransactionsReportAccount {
  /** The Finicity account ID. */
  id: bigint;
  /** The account name from the financial institution. */
  name: string;
  /** The account number from the financial institution (obfuscated). */
  number: string;
  /** All Types: checking, savings, loan, mortgage, credit card, CD, MM, investment, and more. */
  type: AccountTypeEnum;
  /** The status of the most recent aggregation attempt for this account. Note: non-zero means the account was not accessed successfully for this report, and additional fields for this account may not be reliable. */
  aggregationStatusCode: number;
  /** The cleared balance of the account as-of balanceDate. */
  balance: number;
  /** A timestamp showing when the balance was captured. */
  balanceDate: bigint;
  /** A list of transactions associated with the account. */
  transactions: TransactionsReportTransaction[];
  [key: string]: unknown;
}

export const transactionsReportAccountSchema: Schema<TransactionsReportAccount> = expandoObject(
  {
    id: ['id', bigint()],
    name: ['name', string()],
    number: ['number', string()],
    type: ['type', accountTypeEnumSchema],
    aggregationStatusCode: ['aggregationStatusCode', number()],
    balance: ['balance', number()],
    balanceDate: ['balanceDate', bigint()],
    transactions: [
      'transactions',
      array(lazy(() => transactionsReportTransactionSchema)),
    ],
  }
);
