/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, expandoObject, lazy, Schema, string } from '../schema';
import {
  TransactionsReportAccount,
  transactionsReportAccountSchema,
} from './transactionsReportAccount';

/** The fields used for the Transaction History Report (CRA products). */
export interface TransactionsReportInstitution {
  /** The Finicity institution ID. */
  id: bigint;
  /** The Finicity institution name. */
  name: string;
  /** The URL of the financial institution. */
  urlHomeApp: string;
  /** A list of account records. */
  accounts: TransactionsReportAccount[];
  [key: string]: unknown;
}

export const transactionsReportInstitutionSchema: Schema<TransactionsReportInstitution> = expandoObject(
  {
    id: ['id', bigint()],
    name: ['name', string()],
    urlHomeApp: ['urlHomeApp', string()],
    accounts: ['accounts', array(lazy(() => transactionsReportAccountSchema))],
  }
);
