/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  expandoObject,
  lazy,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ReportCustomField,
  reportCustomFieldSchema,
} from './reportCustomField';

export interface TransactionReportConstraints {
  /** Specific accountIds to be included in the new report. */
  accountIds?: string[];
  /** The fromDate parameter is an Epoch Timestamp (in seconds), such as “1494449017”.  Without this parameter, the report defaults to 6 months if available. Example: ?fromDate={fromDate} If included, the epoch timestamp should be 10 digits long and be within two years of the present day. Extending the epoch timestamp beyond 10 digits will default back to six months of data.  This query is optional */
  fromDate?: bigint;
  /** The ending timestamp for the date range. The value must be greater than fromDate. See Handling Dates and Times. */
  toDate?: bigint;
  /** True: Include pending transactions in the report. False: Set by default. */
  includePending?: boolean;
  /** Designate up to 5 custom fields that you would like associated with the report upon generation by providing a label for the field and a value for the field. Set the shown variable to true if you want the custom field to display in the PDF reports. Set the shown variable to false to limit seeing the variable to JSON, XML report but not in the PDF report. All custom fields will display in the Reseller Billing endpoint.  This is optional. */
  reportCustomFields?: ReportCustomField[];
  [key: string]: unknown;
}

export const transactionReportConstraintsSchema: Schema<TransactionReportConstraints> = expandoObject(
  {
    accountIds: ['accountIds', optional(array(string()))],
    fromDate: ['fromDate', optional(bigint())],
    toDate: ['toDate', optional(bigint())],
    includePending: ['includePending', optional(boolean())],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
  }
);
