/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface TxpushSubscriptionRequest {
  /** The TxPUSH Listener URL to receive TxPUSH notifications (must use https protocol for any real-world account) */
  callbackUrl: string;
  [key: string]: unknown;
}

export const txpushSubscriptionRequestSchema: Schema<TxpushSubscriptionRequest> = expandoObject(
  { callbackUrl: ['callbackUrl', string()] }
);
