/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  expandoObject,
  lazy,
  number,
  Schema,
  string,
} from '../schema';
import {
  VOETransactionsReportIncomeStreamRecord,
  vOETransactionsReportIncomeStreamRecordSchema,
} from './vOETransactionsReportIncomeStreamRecord';

export interface VOETransactionsReportAccount {
  /** The generated FInicity ID of the account */
  id: bigint;
  /** The account number from the institution (all digits except the last four are obfuscated) */
  number: string;
  /** The name(s) of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report. */
  ownerName: string;
  /** The mailing address of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report. */
  ownerAddress: string;
  /** The account name from the institution */
  name: string;
  /** One of the values from Account Types */
  type: string;
  /** The status of the most recent aggregation attempt (see Handling Aggregation Status Codes) */
  aggregationStatusCode: number;
  /** A list of income stream records */
  incomeStreams: VOETransactionsReportIncomeStreamRecord[];
  [key: string]: unknown;
}

export const vOETransactionsReportAccountSchema: Schema<VOETransactionsReportAccount> = expandoObject(
  {
    id: ['id', bigint()],
    number: ['number', string()],
    ownerName: ['ownerName', string()],
    ownerAddress: ['ownerAddress', string()],
    name: ['name', string()],
    type: ['type', string()],
    aggregationStatusCode: ['aggregationStatusCode', number()],
    incomeStreams: [
      'incomeStreams',
      array(lazy(() => vOETransactionsReportIncomeStreamRecordSchema)),
    ],
  }
);
