/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, Schema, string } from '../schema';

export interface VOETReportTransactionsForIncomeStreams {
  /** The Finicity ID of the transaction */
  id: bigint;
  /** A timestamp showing when the transaction was posted or cleared by the institution (see Handling Dates and Times) */
  postedDate: bigint;
  /** The description of the transaction, as provided by the institution (often known as payee). In the event that this field is left blank by the institution, Finicity will pass a value of “No description provided by institution”. All other values are provided by the institution. */
  description: string;
  /** A normalized payee, derived from the transaction's description and memo fields. */
  normalizedPayee: string;
  /** The unique identifier given by the FI for each transaction. */
  institutionTransactionId: string;
  /** The categorization of the transaction. */
  category: string;
  [key: string]: unknown;
}

export const vOETReportTransactionsForIncomeStreamsSchema: Schema<VOETReportTransactionsForIncomeStreams> = expandoObject(
  {
    id: ['id', bigint()],
    postedDate: ['postedDate', bigint()],
    description: ['description', string()],
    normalizedPayee: ['normalizedPayee', string()],
    institutionTransactionId: ['institutionTransactionId', string()],
    category: ['category', string()],
  }
);
