/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  optional,
  Schema,
  string,
} from '../schema';

export interface VOIEWithStatementData {
  /** The list of pay statement asset IDs. */
  assetIds: string[];
  /** Field to indicate whether to extract the earnings on all pay statements. This is an optional field. */
  extractEarnings?: boolean;
  /** Field to indicate whether to extract the deductions on all pay statements. This is an optional field. */
  extractDeductions?: boolean;
  /** Field to indicate whether to extract the direct deposits on all pay statements. This is an optional field. */
  extractDirectDeposit?: boolean;
  [key: string]: unknown;
}

export const vOIEWithStatementDataSchema: Schema<VOIEWithStatementData> = expandoObject(
  {
    assetIds: ['assetIds', array(string())],
    extractEarnings: ['extractEarnings', optional(boolean())],
    extractDeductions: ['extractDeductions', optional(boolean())],
    extractDirectDeposit: ['extractDirectDeposit', optional(boolean())],
  }
);
