/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema, string } from '../schema';
import { CadenceDetails, cadenceDetailsSchema } from './cadenceDetails';
import { NetMonthly, netMonthlySchema } from './netMonthly';
import { StatusEnum, statusEnumSchema } from './statusEnum';
import {
  VOIETxverifyReportTransaction,
  vOIETxverifyReportTransactionSchema,
} from './vOIETxverifyReportTransaction';

export interface VOIETxverifyReportIncomeStream {
  /** Finicity’s income stream ID */
  id: string;
  /** A human-readable name based on the normalizedPayee name of the transactions for this income stream */
  name: string;
  /** active or inactive */
  status: StatusEnum;
  /** Level of confidence that the deposit stream represents income (example: 85%) */
  confidence: number;
  cadence: CadenceDetails;
  /** A list of net monthly records. One instance for each complete calendar month in the report */
  netMonthly: NetMonthly[];
  /** Sum of all values in netMonthlyIncome over the previous 12 months */
  netAnnual: number;
  /** Projected net income over the next 12 months, across all income streams, based on netAnnualIncome */
  projectedNetAnnual: number;
  /** Before-tax gross annual income (estimated from netAnnual) across all income stream in the past 12 months */
  estimatedGrossAnnual: number;
  /** Projected gross income over the next 12 months, across all active income streams, based on projectedNetAnnual */
  projectedGrossAnnual: number;
  /** Monthly average amount over the previous 24 months */
  averageMonthlyIncomeNet: number;
  /** The number of months the income transactions are observed */
  incomeStreamMonths: number;
  /** A list of transaction records */
  transactions: VOIETxverifyReportTransaction[];
  [key: string]: unknown;
}

export const vOIETxverifyReportIncomeStreamSchema: Schema<VOIETxverifyReportIncomeStream> = expandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    status: ['status', statusEnumSchema],
    confidence: ['confidence', number()],
    cadence: ['cadence', lazy(() => cadenceDetailsSchema)],
    netMonthly: ['netMonthly', array(lazy(() => netMonthlySchema))],
    netAnnual: ['netAnnual', number()],
    projectedNetAnnual: ['projectedNetAnnual', number()],
    estimatedGrossAnnual: ['estimatedGrossAnnual', number()],
    projectedGrossAnnual: ['projectedGrossAnnual', number()],
    averageMonthlyIncomeNet: ['averageMonthlyIncomeNet', number()],
    incomeStreamMonths: ['incomeStreamMonths', number()],
    transactions: [
      'transactions',
      array(lazy(() => vOIETxverifyReportTransactionSchema)),
    ],
  }
);
