/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  expandoObject,
  lazy,
  number,
  optional,
  Schema,
  string,
} from '../schema';
import { ErrorMessage, errorMessageSchema } from './errorMessage';
import { TypeEnum, typeEnumSchema } from './typeEnum';
import {
  VOIEPaystubWithStatementPayStatement,
  vOIEPaystubWithStatementPayStatementSchema,
} from './vOIEPaystubWithStatementPayStatement';
import {
  VOIEWithStatementConstraints,
  vOIEWithStatementConstraintsSchema,
} from './vOIEWithStatementConstraints';

export interface VOIEPaystubReportRecord {
  /** Finicity's report ID */
  id: string;
  /** Finicity’s portfolio ID associated with the consumer on the report. */
  portfolioId: string;
  /** Finicity Internal Use Only */
  gseEnabled: boolean;
  /** Customer type */
  customerType: string;
  /** Finicity ID for the customer */
  customerId: bigint;
  /** Finicity report consumer ID (max length 32 characters) */
  consumerId: string;
  /** Last 4 digits of the report consumer’s Social Security number */
  consumerSsn: string;
  /** Name of Finicity partner requesting the report */
  requesterName: string;
  /** Unique requestId for this specific call request */
  requestId: string;
  /** Report type */
  type: TypeEnum;
  /** inProgress, success, or failure */
  status: string;
  /** The date the report was generated */
  createdDate: bigint;
  /** Title of the report */
  title: string;
  /** voieWithStatement */
  reportStyle: string;
  constraints: VOIEWithStatementConstraints;
  /** The pay statements included in the report */
  assetIds: string[];
  /** Total number of billable pay statements included in the report */
  numberOfBillableAssets: number;
  /** Extracted pay statement details, and the transaction matching summary */
  payStatements: VOIEPaystubWithStatementPayStatement[];
  errors?: ErrorMessage[];
  [key: string]: unknown;
}

export const vOIEPaystubReportRecordSchema: Schema<VOIEPaystubReportRecord> = expandoObject(
  {
    id: ['id', string()],
    portfolioId: ['portfolioId', string()],
    gseEnabled: ['gseEnabled', boolean()],
    customerType: ['customerType', string()],
    customerId: ['customerId', bigint()],
    consumerId: ['consumerId', string()],
    consumerSsn: ['consumerSsn', string()],
    requesterName: ['requesterName', string()],
    requestId: ['requestId', string()],
    type: ['type', typeEnumSchema],
    status: ['status', string()],
    createdDate: ['createdDate', bigint()],
    title: ['title', string()],
    reportStyle: ['reportStyle', string()],
    constraints: [
      'constraints',
      lazy(() => vOIEWithStatementConstraintsSchema),
    ],
    assetIds: ['assetIds', array(string())],
    numberOfBillableAssets: ['numberOfBillableAssets', number()],
    payStatements: [
      'payStatements',
      array(lazy(() => vOIEPaystubWithStatementPayStatementSchema)),
    ],
    errors: ['errors', optional(array(lazy(() => errorMessageSchema)))],
  }
);
