/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountTypeEnum
 */
export enum AccountTypeEnum {
  Checking = 'checking',
  Savings = 'savings',
  Cd = 'cd',
  MoneyMarket = 'moneyMarket',
  CreditCard = 'creditCard',
  LineOfCredit = 'lineOfCredit',
  Investment = 'investment',
  InvestmentTaxDeferred = 'investmentTaxDeferred',
  EmployeeStockPurchasePlan = 'employeeStockPurchasePlan',
  Ira = 'ira',
  M401k = '401k',
  Roth = 'roth',
  M403b = '403b',
  M529plan = '529plan',
  Rollover = 'rollover',
  Ugma = 'ugma',
  Utma = 'utma',
  Keogh = 'keogh',
  M457plan = '457plan',
  M401a = '401a',
  Mortgage = 'mortgage',
  Loan = 'loan',
  StudentLoan = 'studentLoan',
  StudentLoanGroup = 'studentLoanGroup',
  StudentLoanAccount = 'studentLoanAccount',
}

/**
 * Schema for AccountTypeEnum
 */
export const accountTypeEnumSchema: Schema<AccountTypeEnum> = stringEnum(AccountTypeEnum);
