/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema, string } from '../schema';

export interface CashFlowMonthlyCashFlowCredits {
  /** One instance for each complete calendar month in the report */
  month: bigint;
  /** Number of credits by month */
  numberOfCredits: string;
  /** Total amount of credits by month */
  totalCreditsAmount: number;
  /** Largest credit by month */
  largestCredit: number;
  /** Number of credits by month (less transfers) */
  numberOfCreditsLessTransfers: string;
  /** Total amount of credits by month (less transfers) */
  totalCreditsAmountLessTransfers: number;
  /** The average credit amount */
  averageCreditAmount: number;
  /** The estimated number of loan deposits */
  estimatedNumberOfLoanDeposits: string;
  /** The estimated loan deposit amount */
  estimatedLoanDepositAmount: number;
  [key: string]: unknown;
}

export const cashFlowMonthlyCashFlowCreditsSchema: Schema<CashFlowMonthlyCashFlowCredits> = expandoObject(
  {
    month: ['month', bigint()],
    numberOfCredits: ['numberOfCredits', string()],
    totalCreditsAmount: ['totalCreditsAmount', number()],
    largestCredit: ['largestCredit', number()],
    numberOfCreditsLessTransfers: ['numberOfCreditsLessTransfers', string()],
    totalCreditsAmountLessTransfers: [
      'totalCreditsAmountLessTransfers',
      number(),
    ],
    averageCreditAmount: ['averageCreditAmount', number()],
    estimatedNumberOfLoanDeposits: ['estimatedNumberOfLoanDeposits', string()],
    estimatedLoanDepositAmount: ['estimatedLoanDepositAmount', number()],
  }
);
