/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema, string } from '../schema';

export interface CashFlowMonthlyCashFlowBalances {
  /** One instance for each complete calendar month in the report */
  month: bigint;
  /** Min Daily Balance for each month */
  minDailyBalance: number;
  /** Max Daily Balance for each month */
  maxDailyBalance: number;
  /** Average Daily Balance for each month */
  averageDailyBalance: number;
  /** Standard Deviation of Daily Balance for each month */
  standardDeviationOfDailyBalance: string;
  /** Number of Days Negative Balance for each month */
  numberOfDaysNegativeBalance: string;
  /** Number of Days positive balance for each month */
  numberOfDaysPositiveBalance: string;
  [key: string]: unknown;
}

export const cashFlowMonthlyCashFlowBalancesSchema: Schema<CashFlowMonthlyCashFlowBalances> = expandoObject(
  {
    month: ['month', bigint()],
    minDailyBalance: ['minDailyBalance', number()],
    maxDailyBalance: ['maxDailyBalance', number()],
    averageDailyBalance: ['averageDailyBalance', number()],
    standardDeviationOfDailyBalance: [
      'standardDeviationOfDailyBalance',
      string(),
    ],
    numberOfDaysNegativeBalance: ['numberOfDaysNegativeBalance', string()],
    numberOfDaysPositiveBalance: ['numberOfDaysPositiveBalance', string()],
  }
);
