/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, number, Schema } from '../schema';
import {
  CashFlowMonthlyCashFlowCharacteristics,
  cashFlowMonthlyCashFlowCharacteristicsSchema,
} from './cashFlowMonthlyCashFlowCharacteristics';

export interface CashFlowCashflowCharacteristic {
  /** List of attributes for each month */
  monthlyCashFlowCharacteristics: CashFlowMonthlyCashFlowCharacteristics[];
  /** Average (Total Credits - Total Debits) for the account */
  averageMonthlyNet: number;
  /** Average (Total Credits - Total Debits) without transfers for the account */
  averageMonthlyNetLessTransfers: number;
  /** Sum of all monthly (Total Credits - Total Debits) each month for the account */
  twelveMonthTotalNet: number;
  /** Sum of all monthly (Total Credits - Total Debits) without transfers for the account */
  twelveMonthTotalNetLessTransfers: number;
  /** 6 Month Average (Total Credits - Total Debits) */
  sixMonthAverageTotalCreditsLessTotalDebits: number;
  /** 6 Month Average (Total Credits - Total Debits) - (Without Transfers) */
  sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers: number;
  /** 2 Month Average (Total Credits - Total Debits) */
  twoMonthAverageTotalCreditsLessTotalDebits: number;
  /** 2 Month Average (Total Credits - Total Debits) - (Without Transfers) */
  twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers: number;
  [key: string]: unknown;
}

export const cashFlowCashflowCharacteristicSchema: Schema<CashFlowCashflowCharacteristic> = expandoObject(
  {
    monthlyCashFlowCharacteristics: [
      'monthlyCashFlowCharacteristics',
      array(lazy(() => cashFlowMonthlyCashFlowCharacteristicsSchema)),
    ],
    averageMonthlyNet: ['averageMonthlyNet', number()],
    averageMonthlyNetLessTransfers: [
      'averageMonthlyNetLessTransfers',
      number(),
    ],
    twelveMonthTotalNet: ['twelveMonthTotalNet', number()],
    twelveMonthTotalNetLessTransfers: [
      'twelveMonthTotalNetLessTransfers',
      number(),
    ],
    sixMonthAverageTotalCreditsLessTotalDebits: [
      'sixMonthAverageTotalCreditsLessTotalDebits',
      number(),
    ],
    sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers: [
      'sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers',
      number(),
    ],
    twoMonthAverageTotalCreditsLessTotalDebits: [
      'twoMonthAverageTotalCreditsLessTotalDebits',
      number(),
    ],
    twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers: [
      'twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers',
      number(),
    ],
  }
);
