/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema, string } from '../schema';
import { CashFlowAccount, cashFlowAccountSchema } from './cashFlowAccount';

export interface CashFlowInstitution {
  /** Finicity institution ID */
  id: string;
  /** Finicity institution name */
  name: string;
  /** The URL of the Financial Institution */
  urlHomeApp: string;
  /** A list of `account` records */
  accounts: CashFlowAccount[];
  [key: string]: unknown;
}

export const cashFlowInstitutionSchema: Schema<CashFlowInstitution> = expandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    urlHomeApp: ['urlHomeApp', string()],
    accounts: ['accounts', array(lazy(() => cashFlowAccountSchema))],
  }
);
