/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema, string } from '../schema';
import {
  CashFlowPossibleLoanDepositsAccount,
  cashFlowPossibleLoanDepositsAccountSchema,
} from './cashFlowPossibleLoanDepositsAccount';

export interface CashFlowPossibleLoanDeposits {
  /** Finicity institution ID */
  id: string;
  /** Finicity institution name */
  name: string;
  /** The URL of the Financial Institution */
  urlHomeApp: string;
  /** A list of `account` records */
  accounts: CashFlowPossibleLoanDepositsAccount[];
  [key: string]: unknown;
}

export const cashFlowPossibleLoanDepositsSchema: Schema<CashFlowPossibleLoanDeposits> = expandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    urlHomeApp: ['urlHomeApp', string()],
    accounts: [
      'accounts',
      array(lazy(() => cashFlowPossibleLoanDepositsAccountSchema)),
    ],
  }
);
