/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, expandoObject, number, Schema, string } from '../schema';

export interface CashFlowMonthlycashflowDebits {
  /** One instance for each complete calendar month in the report */
  month: bigint;
  /** Number of Debits by month */
  numberOfDebits: string;
  /** Total Amount of Debits by month */
  totalDebitsAmount: number;
  /** Largest Debit by month */
  largestDebit: number;
  /** Number of Debits by month (less transfers) */
  numberOfDebitsLessTransfers: string;
  /** Total amount of debits by month (less transfers) */
  totalDebitsAmountLessTransfers: number;
  /** The average debit amount */
  averageDebitAmount: number;
  [key: string]: unknown;
}

export const cashFlowMonthlycashflowDebitsSchema: Schema<CashFlowMonthlycashflowDebits> = expandoObject(
  {
    month: ['month', bigint()],
    numberOfDebits: ['numberOfDebits', string()],
    totalDebitsAmount: ['totalDebitsAmount', number()],
    largestDebit: ['largestDebit', number()],
    numberOfDebitsLessTransfers: ['numberOfDebitsLessTransfers', string()],
    totalDebitsAmountLessTransfers: [
      'totalDebitsAmountLessTransfers',
      number(),
    ],
    averageDebitAmount: ['averageDebitAmount', number()],
  }
);
