/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

/** Categorization Record */
export interface Categorization {
  /** A normalized payee, derived from the transaction’s description and memo fields. */
  normalizedPayeeName?: string;
  /** One of the values from Categories (assigned based on the payee name) */
  category?: string;
  /** City of transaction (if available) */
  city?: string;
  /** State of transaction (if available) */
  state?: string;
  postalCode?: string;
  /** Country where the transaction occurred */
  country?: string;
  bestRepresentation?: string;
  [key: string]: unknown;
}

export const categorizationSchema: Schema<Categorization> = expandoObject({
  normalizedPayeeName: ['normalizedPayeeName', optional(string())],
  category: ['category', optional(string())],
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  postalCode: ['postalCode', optional(string())],
  country: ['country', optional(string())],
  bestRepresentation: ['bestRepresentation', optional(string())],
});
