/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

export interface Categorization1 {
  normalizedPayeeName: string;
  category: string;
  country: string;
  [key: string]: unknown;
}

export const categorization1Schema: Schema<Categorization1> = expandoObject({
  normalizedPayeeName: ['normalizedPayeeName', string()],
  category: ['category', string()],
  country: ['country', string()],
});
