/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string, unknown } from '../schema';

export interface ConsumerAttributesDataExpenses {
  /** Total dwelling expenses for the last 12 months: rent, mortgage, utilities, and insurance. */
  dwellingExpenseTotal: string;
  /** Total dwelling expenses by account for the last 12 months: rent, mortgage, utilities, and insurance. */
  dwellingExpensesByAccount?: unknown;
  /** Monthly dwelling expenses by customer. */
  monthlyDwellingExpenseByCustomer?: unknown;
  /** Monthly dwelling expenses by account. */
  monthlyDwellingExpenseByAccount?: unknown;
  /** Total monthly debit amounts by customer. */
  monthlyDebitAmountByCustomer?: unknown;
  /** Total monthly debit amounts, excluding transfers and credit card payments. */
  monthlyExpenseAmountByCustomer?: unknown;
  [key: string]: unknown;
}

export const consumerAttributesDataExpensesSchema: Schema<ConsumerAttributesDataExpenses> = expandoObject(
  {
    dwellingExpenseTotal: ['dwellingExpenseTotal', string()],
    dwellingExpensesByAccount: ['dwellingExpensesByAccount', unknown()],
    monthlyDwellingExpenseByCustomer: [
      'monthlyDwellingExpenseByCustomer',
      unknown(),
    ],
    monthlyDwellingExpenseByAccount: [
      'monthlyDwellingExpenseByAccount',
      unknown(),
    ],
    monthlyDebitAmountByCustomer: ['monthlyDebitAmountByCustomer', unknown()],
    monthlyExpenseAmountByCustomer: [
      'monthlyExpenseAmountByCustomer',
      unknown(),
    ],
  }
);
