/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  expandoObject,
  number,
  optional,
  Schema,
  string,
} from '../schema';

export interface ErrorMessage {
  /** Error code */
  code: number;
  /** Error message */
  message?: string;
  /** Finicity's asset ID */
  assetId?: string;
  /** The generated Finicity ID of the account that had the error */
  accountId?: bigint;
  [key: string]: unknown;
}

export const errorMessageSchema: Schema<ErrorMessage> = expandoObject({
  code: ['code', number()],
  message: ['message', optional(string())],
  assetId: ['assetId', optional(string())],
  accountId: ['accountId', optional(bigint())],
});
