/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema, string } from '../schema';
import {
  ConnectV2EmailOptions,
  connectV2EmailOptionsSchema,
} from './connectV2EmailOptions';

/** The response from the send email endpoint. */
export interface GenerateV2ConnectEmailResponse {
  /** The URL generated to send a Connect email */
  link: string;
  /** The configuration used to generate the Connect email. */
  emailConfig: ConnectV2EmailOptions;
  [key: string]: unknown;
}

export const generateV2ConnectEmailResponseSchema: Schema<GenerateV2ConnectEmailResponse> = expandoObject(
  {
    link: ['link', string()],
    emailConfig: ['emailConfig', lazy(() => connectV2EmailOptionsSchema)],
  }
);
