/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  expandoObject,
  lazy,
  number,
  Schema,
} from '../schema';
import { Institution, institutionSchema } from './institution';

/** A list of Finicity financial institutions from the standard get institutions response */
export interface GetInstitutionsResponse {
  /** Total number of results found */
  found: number;
  /** Display the results count */
  displaying: number;
  /** **True**: There are more institutions, matching the search parameters, that you can display. */
  moreAvailable: boolean;
  /** Date the request was created */
  createdDate: bigint;
  /** An array of institutions */
  institutions: Institution[];
  [key: string]: unknown;
}

export const getInstitutionsResponseSchema: Schema<GetInstitutionsResponse> = expandoObject(
  {
    found: ['found', number()],
    displaying: ['displaying', number()],
    moreAvailable: ['moreAvailable', boolean()],
    createdDate: ['createdDate', bigint()],
    institutions: ['institutions', array(lazy(() => institutionSchema))],
  }
);
