/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

export interface LoanPaymentDetailsLoanDetail {
  /** Finicity's ID of the Student Loan */
  accountId: string;
  /** Institution's ID of the Student Loan */
  loanNumber: string;
  /** The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number. */
  loanPaymentNumber: string;
  /** The payment address to which send manual payments should be sent */
  loanPaymentAddress: string;
  /** The payoff amount for the loan */
  loanFuturePayoffAmount?: number;
  /** The date to which the `Future Payoff Amount` applies */
  loanFuturePayoffDate?: string;
  [key: string]: unknown;
}

export const loanPaymentDetailsLoanDetailSchema: Schema<LoanPaymentDetailsLoanDetail> = expandoObject(
  {
    accountId: ['accountId', string()],
    loanNumber: ['loanNumber', string()],
    loanPaymentNumber: ['loanPaymentNumber', string()],
    loanPaymentAddress: ['loanPaymentAddress', string()],
    loanFuturePayoffAmount: ['loanFuturePayoffAmount', optional(number())],
    loanFuturePayoffDate: ['loanFuturePayoffDate', optional(string())],
  }
);
