/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  expandoObject,
  lazy,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PayrollEmployeeAddress,
  payrollEmployeeAddressSchema,
} from './payrollEmployeeAddress';

export interface PayrollEmployeeRecord {
  /** Full name of the employee: first, middle (if stated), and last name. */
  name: string;
  /** First name of employee */
  givenName: string;
  /** Middle name of employee, if stated */
  middleName?: string;
  /** Last name of employee */
  familyName: string;
  /** Array of addresses */
  address?: PayrollEmployeeAddress[];
  [key: string]: unknown;
}

export const payrollEmployeeRecordSchema: Schema<PayrollEmployeeRecord> = expandoObject(
  {
    name: ['name', string()],
    givenName: ['givenName', string()],
    middleName: ['middleName', optional(string())],
    familyName: ['familyName', string()],
    address: [
      'address',
      optional(array(lazy(() => payrollEmployeeAddressSchema))),
    ],
  }
);
