/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, optional, Schema, string } from '../schema';

export interface Subaccount {
  subaccountNumber?: string;
  subaccountName?: string;
  [key: string]: unknown;
}

export const subaccountSchema: Schema<Subaccount> = expandoObject({
  subaccountNumber: ['subaccountNumber', optional(string())],
  subaccountName: ['subaccountName', optional(string())],
});
