/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, expandoObject, lazy, Schema, string } from '../schema';
import {
  VOAWithIncomeReportAccount,
  vOAWithIncomeReportAccountSchema,
} from './vOAWithIncomeReportAccount';

export interface VOAWithIncomeReportInstitution {
  /** The institution ID */
  id: bigint;
  /** The name of the institution */
  name: string;
  /** The URL of the institution’s primary home page */
  urlHomeApp: string;
  /** An array of accounts */
  accounts: VOAWithIncomeReportAccount[];
  [key: string]: unknown;
}

export const vOAWithIncomeReportInstitutionSchema: Schema<VOAWithIncomeReportInstitution> = expandoObject(
  {
    id: ['id', bigint()],
    name: ['name', string()],
    urlHomeApp: ['urlHomeApp', string()],
    accounts: ['accounts', array(lazy(() => vOAWithIncomeReportAccountSchema))],
  }
);
