/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, optional, Schema } from '../schema';
import {
  ReportCustomField,
  reportCustomFieldSchema,
} from './reportCustomField';
import {
  VOIEWithStatementData,
  vOIEWithStatementDataSchema,
} from './vOIEWithStatementData';

/** The request details from the report generation that were used to generate the report */
export interface VOIEWithStatementConstraints {
  /** The asset Ids (generated using the Store Customer Pay Statment API) for the paystubs included in the report, and other report optional report constraints. */
  voieWithStatementData: VOIEWithStatementData;
  /** Designate up to 5 custom fields that you would like associated with the report upon generation by providing a label for the field and a value for the field. Set the shown variable to true if you want the custom field to display in the PDF reports. Set the shown variable to false to limit seeing the variable to JSON, XML report but not in the PDF report. All custom fields will display in the Reseller Billing endpoint.  This is optional. */
  reportCustomFields?: ReportCustomField[];
  [key: string]: unknown;
}

export const vOIEWithStatementConstraintsSchema: Schema<VOIEWithStatementConstraints> = expandoObject(
  {
    voieWithStatementData: [
      'voieWithStatementData',
      lazy(() => vOIEWithStatementDataSchema),
    ],
    reportCustomFields: [
      'reportCustomFields',
      optional(array(lazy(() => reportCustomFieldSchema))),
    ],
  }
);
