/**
 * Finicity APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, expandoObject, lazy, Schema, string } from '../schema';
import {
  VOIReportAccountRecord,
  vOIReportAccountRecordSchema,
} from './vOIReportAccountRecord';

/** VOI Report Institution Record */
export interface VOIReportInstitutionRecord {
  /** The institution ID */
  id: bigint;
  /** The name of the institution */
  name: string;
  /** The URL of the institution’s primary home page */
  urlHomeApp: string;
  /** An array of accounts */
  accounts: VOIReportAccountRecord[];
  [key: string]: unknown;
}

export const vOIReportInstitutionRecordSchema: Schema<VOIReportInstitutionRecord> = expandoObject(
  {
    id: ['id', bigint()],
    name: ['name', string()],
    urlHomeApp: ['urlHomeApp', string()],
    accounts: ['accounts', array(lazy(() => vOIReportAccountRecordSchema))],
  }
);
